objs += \
$(ROOT)/apps/common/product_test_tool/product_main.o \
$(ROOT)/apps/common/product_test_tool/product_port.o \
$(ROOT)/apps/common/product_test_tool/communication.o \
$(ROOT)/apps/common/product_test_tool/devices_control.o \

includes += \
-I$(ROOT)/apps/common/product_test_tool/includes/ \
-I$(ROOT)/lib/include/usb/usb_core/ \

