
objs += \
$(ROOT)/apps/common/rf_fcc_tool/wifi_moudle.o \
$(ROOT)/apps/common/rf_fcc_tool/communication.o \
$(ROOT)/apps/common/rf_fcc_tool/rf_fcc_main.o \

includes += \
-I$(ROOT)/apps/common/rf_fcc_tool/includes \
-I$(ROOT)/lib/net/device/wireless/WIFI_todo \


