objs += \
$(ROOT)/cpu/$(CPU)/setup.o \
$(ROOT)/cpu/$(CPU)/debug.o \
$(ROOT)/cpu/$(CPU)/adc.o \
$(ROOT)/cpu/$(CPU)/adkey.o \
$(ROOT)/cpu/$(CPU)/iokey.o \
$(ROOT)/cpu/$(CPU)/ldo.o \
$(ROOT)/cpu/$(CPU)/power_inf.o \
$(ROOT)/cpu/$(CPU)/static_memory_alloc.o \
$(ROOT)/cpu/$(CPU)/uart_key.o \

#dvp lcd
objs += \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_480x272.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_480x272_8bits.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_480x272_18bits.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_avout.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_avout_hd.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_HX8369A_MCU.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_HX8369A_SPI_RGB.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_ILI8960.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_ILI9806.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_LQ026B3UX01.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_LX50FWB4001_V2.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_LYWS030GQ.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_ssd1963.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_ST7789S.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_T15P00.o \
$(ROOT)/cpu/$(CPU)/dvp_lcd_driver/lcd_virtual.o \


#lvds lcd
objs += \
$(ROOT)/cpu/$(CPU)/lvds_lcd_driver/lvds_1024x600.o \
$(ROOT)/cpu/$(CPU)/lvds_lcd_driver/lvds_1280x800.o \
$(ROOT)/cpu/$(CPU)/lvds_lcd_driver/lvds_1920x480.o \



#lvds lcd
objs += \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_dcs_1lane_16bit.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_dcs_1lane_24bit.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_2lane_1280x480_EK79030.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_2lane_24bit.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_2lane_st7701s.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_2lane_bs_t40_l4.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_4lane_1080p.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_4lane_1280x480_EK79030.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_4lane_720p.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/dsi_vdo_4lane_720p_rm68200ga1.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/lcd_mipi_4lane_s8500l0.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1280x400_wt.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1280x480.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1280x480_ICN9706.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1280x720_RM68200GA1.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1600x400_wt1098802g01.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1600x400_wt1098802g01_1.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1920x380_OTA7290B.o \
$(ROOT)/cpu/$(CPU)/mipi_lcd_driver/mipi_lcd_1920x480_OTA7290B.o \


