
objs += \
	$(ROOT)/camera/gc1034/gc1034.o \
	$(ROOT)/camera/gc1034/gc1034_ae.o \
	$(ROOT)/camera/gc1034/gc1034_awb.o \
	$(ROOT)/camera/gc1034/gc1034_iq.o \
	$(ROOT)/camera/gc2043_dvp/gc2043.o \
	$(ROOT)/camera/gc2043_dvp/gc2043_ae.o \
	$(ROOT)/camera/gc2043_dvp/gc2043_awb.o \
	$(ROOT)/camera/gc2043_dvp/gc2043_iq.o \
	$(ROOT)/camera/sc1243_dvp/sc1243.o \
	$(ROOT)/camera/sc1243_dvp/sc1243_ae.o \
	$(ROOT)/camera/sc1243_dvp/sc1243_awb.o \
	$(ROOT)/camera/sc1243_dvp/sc1243_iq.o \
	$(ROOT)/camera/gc1004/gc1004.o \
	$(ROOT)/camera/gc1004/gc1004_ae.o \
	$(ROOT)/camera/gc1004/gc1004_awb.o \
	$(ROOT)/camera/gc1004/gc1004_iq.o \
	$(ROOT)/camera/av10/av10_spi.o \
	$(ROOT)/camera/av10/av10.o \
	$(ROOT)/camera/gm7150/gm7150.o \
	$(ROOT)/camera/tp2850/tp2850.o \
	$(ROOT)/camera/pr1000/pr1000.o \
	$(ROOT)/camera/pr2000/pr2000k.o \
	$(ROOT)/camera/tp9930/tp9930.o \
	$(ROOT)/camera/sc2313_dvp/sc2313.o \
	$(ROOT)/camera/sc2313_dvp/sc2313_ae.o \
	$(ROOT)/camera/sc2313_dvp/sc2313_awb.o \
	$(ROOT)/camera/sc2313_dvp/sc2313_iq.o \
	$(ROOT)/camera/h42/h42.o \
	$(ROOT)/camera/h42/h42_ae.o \
	$(ROOT)/camera/h42/h42_awb.o \
	$(ROOT)/camera/h42/h42_iq.o \
	$(ROOT)/camera/bg0806_mipi/bg0806_mipi.o \
	$(ROOT)/camera/bg0806_mipi/bg0806_mipi_ae.o \
	$(ROOT)/camera/bg0806_mipi/bg0806_mipi_awb.o \
	$(ROOT)/camera/bg0806_mipi/bg0806_mipi_iq.o \
	$(ROOT)/camera/sc2313_mipi/sc2313_mipi.o \
	$(ROOT)/camera/sc2313_mipi/sc2313_mipi_ae.o \
	$(ROOT)/camera/sc2313_mipi/sc2313_mipi_awb.o \
	$(ROOT)/camera/sc2313_mipi/sc2313_mipi_iq.o \
	$(ROOT)/camera/gc2053_mipi/gc2053_mipi.o \
	$(ROOT)/camera/gc2053_mipi/gc2053_mipi_ae.o \
	$(ROOT)/camera/gc2053_mipi/gc2053_mipi_awb.o \
	$(ROOT)/camera/gc2053_mipi/gc2053_mipi_iq.o \
	$(ROOT)/camera/f23_mipi/f23_mipi.o \
	$(ROOT)/camera/f23_mipi/f23_mipi_ae.o \
	$(ROOT)/camera/f23_mipi/f23_mipi_awb.o \
	$(ROOT)/camera/f23_mipi/f23_mipi_iq.o \
	$(ROOT)/camera/F37_mipi/F37_mipi.o \
	$(ROOT)/camera/F37_mipi/F37_mipi_ae.o \
	$(ROOT)/camera/F37_mipi/F37_mipi_awb.o \
	$(ROOT)/camera/F37_mipi/F37_mipi_iq.o \




